language: c

before_install:
  - sudo apt-get update -q
  - sudo apt-get install -qq apt-transport-https python-docutils
  - wget -q https://repo.varnish-cache.org/pkg/5.0.0/varnish_5.0.0-1_amd64.deb https://repo.varnish-cache.org/pkg/5.0.0/varnish-dev_5.0.0-1_amd64.deb
  - dpkg -i varnish_5.0.0-1_amd64.deb varnish-dev_5.0.0-1_amd64.deb


before_script:
  - ./bootstrap --prefix=/usr
  - ./configure --prefix=/usr
  - make -j4

script:
  - make check -j4

compiler:
  - clang
  - gcc
